# Site settings
author: Adam Dudley
title: Truthy Juicy
header-img: img/home-bg.png
email: dudleyadam@gmail.com
copyright_name: Adam Dudley
description: > # this means to ignore newlines until "baseurl:"
  Compelling and truthful writings about code and life.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  adudley78

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
